name: attendance
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  shared_preferences: ^2.2.2
  
  
  provider: ^6.1.2
  
  supabase_flutter: ^2.5.0
  flutter_zxing: ^1.8.2
  mobile_scanner: ^6.0.7
  slide_to_act: ^2.0.2
  lottie: ^3.3.1
  mongo_dart: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/hero.png


